[project]
authors = ["Benjamin Rombaut <benjamin.rombaut@gmail.com>"]
channels = ["conda-forge", "pytorch"]
name = "harpy_figures"
platforms = [ "linux-64"]
version = "0.1.0"

[dependencies]
python = "<3.13"
numpy = ">=1.26.4,<2"
matplotlib = ">=3,<4"
loguru = ">=0.7.2,<0.8"
memray = ">=1.15.0,<2"
hyperfine = ">=1.19.0,<2"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
con-duct = { version = ">=0.10.1, <0.11", extras = ["all"] }
# needed for xr_spatial and flowsom
xarray-spatial = "<0.4.0"
spatialdata = "==0.4.0"
numba = ">=0.55.0"
# segmentation models
instanseg-torch = { git = "https://github.com/berombau/instanseg.git"}
cellpose = "==3.0.11"

[tasks]
prep_datasets = "python prep_datasets.py"
benchmark = "python run_duct_benchmark.py"
test_benchmark = "python run_duct_test_benchmark.py"

[environments]
harpy = ["harpy"]
sopa = ["sopa"]
squidpy = ["squidpy"]
notebook = ['notebook']

[feature.squidpy.dependencies]
scipy = ">=1.14.1,<2"
scikit-image = "<0.25"
pytorch = ">=2.2.2,<3"
geopandas = ">=1.0.1,<2"
dask = ">=2024.4.1,<=2024.11.2"
torchvision = "<0.21"
rasterio = ">=1.4.3,<2"
# fsspec = "<=2023.6"
# dask = ">=2022.3.0,<2023"


[feature.sopa.dependencies]
scipy = ">=1.14.1,<2"
scikit-image = "<0.25"
pytorch = ">=2.2.2,<3"
geopandas = ">=1.0.1,<2"
dask = ">=2024.4.1,<=2024.11.2"
torchvision = "<0.21"
rasterio = ">=1.4.3,<2"
fsspec = "<=2023.6"
# dask = ">=2022.3.0,<2023"

[feature.harpy.dependencies]
scipy = ">=1.14.1,<2"
scikit-image = ">=0.24.0,<0.25"
pytorch = ">=2.2.2,<3"
geopandas = ">=1.0.1,<2"
dask = ">=2024.4.1,<=2024.11.2"
torchvision = "<0.21"
rasterio = ">=1.4.3,<2"
fsspec = "<=2023.6"

[feature.harpy.pypi-dependencies]
anndata = ">=0.9.1,<=0.10.8"
# TODO: fix problem with visium_hd reader in 0.1.7 and spatialdata 0.2.6
# instanseg-torch = { git = "https://github.com/berombau/instanseg.git"}
harpy-analysis = { git = "https://github.com/saeyslab/harpy.git", rev = "d28e245"}
flowsom = { git = "https://github.com/saeyslab/FlowSOM_Python.git", rev = "d8cb6a5" }
pyflowsom = "==0.1.16"
numba = ">=0.55.0"
spatialdata_io = "==0.2.0"
ome_types = "<0.6.0"
spatialdata-plot = ">=0.2.10, <0.3"
supervenn = ">=0.5.0, <0.6"

# instanseg-torch = "==0.0.8"

[feature.sopa.pypi-dependencies]
# TODO: fix problem with visium_hd reader in 0.1.7 and spatialdata 0.2.6
# spatialdata = "==0.3.0"
sopa = "==2.0.1"

[feature.squidpy.pypi-dependencies]
# TODO: fix problem with visium_hd reader in 0.1.7 and spatialdata 0.2.6
squidpy = "==1.6.5"

[feature.notebook.pypi-dependencies]
ipykernel = ">=6.29.5,<7"

[feature.notebook.dependencies]
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.2.3,<3"
numpy = ">=1.26.4,<2"
# seaborn = ">=0.13.2,<0.14"
