[project]
authors = ["Benjamin Rombaut <benjamin.rombaut@gmail.com>"]
channels = ["conda-forge", "pytorch"]
name = "harpy_figures"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = "<3.13"
numpy = ">=1.26.4,<2"
matplotlib = ">=3,<4"
loguru = ">=0.7.2,<0.8"
memray = ">=1.15.0,<2"
hyperfine = ">=1.19.0,<2"
ipykernel = ">=6.29.5,<7"
seaborn = ">=0.13.2,<0.14"

[environments]
all = ["harpy", "dev"]

[feature.dev.dependencies]
ipython = "*"

[feature.harpy.tasks]
prep_datasets = "python prep_datasets.py"
test_benchmark = "python run_duct_test_benchmark.py"

[feature.harpy.dependencies]
scipy = ">=1.14.1,<2"
scikit-image = ">=0.24.0,<0.25"
pytorch = ">=2.2.2,<3"
geopandas = ">=1.0.1,<2"
dask = ">=2024.4.1,<=2024.11.2"
torchvision = "<0.21"
rasterio = ">=1.4.3,<2"
cellpose = ">=3.0.11,<4"
fsspec = "<=2023.6"
# dask = ">=2022.3.0,<2023"

[feature.harpy.pypi-dependencies]
anndata = ">=0.9.1,<=0.10.8"
spatialdata = ">=0.2.6"
# TODO: fix problem with visium_hd reader in 0.1.7 and spatialdata 0.2.6
spatialdata_io = "==0.1.6"
harpy-analysis = { git = "https://github.com/saeyslab/harpy.git", rev = "b7d1c04" }

[pypi-dependencies]
con-duct = { version = ">=0.10.1, <0.11", extras = ["all"] }

